class AppStrings {
  const AppStrings._();
  static const String noRouteFound = "no route found";
  static const String onBoardingTitle1 = "on boarding title1";
  static const String onBoardingTitle2 = "on boarding title2";
  static const String onBoardingTitle3 = "on boardingtitle3";
  static const String onBoardingTitle4 = "on boardingtitle4";

  static const String onBoardingSubTitle1 = "on boarding_desc";
  static const String onBoardingSubTitle2 = "on boarding desc2";
  static const String onBoardingSubTitle3 = "on boarding desc3";
  static const String onBoardingSubTitle4 = "on boarding desc4";
  static const String skip = "skip";
  static const String username = "username hint";
  static const String mobileNumber = "mobile number hint";
  static const String usernameError = "invalid user name";
  static const String passwordError = "invalid password";
  static const String password = "password hint";
  static const String login = "login button";
  static const String forgetPassword = "forgot password text";
  static const String registerText = "register text";
  static const String loading = "loading";
  static const String retryAgain = "retry again";
  static const String ok = "ok";
  static const String emailHint = 'email hint';
  static const String invalidEmail = "invalid email";
  static const String resetPassword = "reset password";
  static const String success = "success";
  static const String profilePicture = "upload profile picture";
  static const String photoGalley = "photo gallery";
  static const String photoCamera = "camera";
  static const String register = "register";
  static const String haveAccount = "already have account";
  static const String home = "home";
  static const String notifications = "notification";
  static const String search = "search";
  static const String settings = "settings";
  static const String services = "services";
  static const String stores = "stores";
  static const String details = "details";
  static const String about = "about";
  static const String storeDetails = "store details";
  static const String changeLanguage = "change language";
  static const String contactUs = "contact us";
  static const String inviteYourFriends = "invite your friends";
  static const String logout = "logout";

  // error handler
  static const String badRequestError = "bad request error";
  static const String noContent = "no content";
  static const String forbiddenError = "forbidden error";
  static const String unauthorizedError = "unauthorized error";
  static const String notFoundError = "not found error";
  static const String conflictError = "conflict error";
  static const String internalServerError = "internal server error";
  static const String unknownError = "unknown error";
  static const String timeoutError = "timeout error";
  static const String defaultError = "default error";
  static const String cacheError = "cache error";
  static const String noInternetError = "no internet error";
}
